server:
  port: 8003
spring:
  application:
    name: service_vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  vod:
    file:
      keyId: LTAI4GBZaZvoVyPtM3CmoH8r
      keySecret: tHJ1mihPEUZbGlia1PD74yzr8Xdom5
