spring:
  application:
    name: service-cms
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/online_school?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 20000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
server:
  port: 8004