server:
  port: 8005
spring:
  application:
    name: service-msm
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
aliyun:
  msm:
    keyId: LTAI4GBZaZvoVyPtM3CmoH8r
    keySecret: tHJ1mihPEUZbGlia1PD74yzr8Xdom5