server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyId: LTAI4GBZaZvoVyPtM3CmoH8r
      keySecret: tHJ1mihPEUZbGlia1PD74yzr8Xdom5
      bucketName: edu0125